package main

import (
	"fmt"
	"os"
	"vectos/internal/buildinfo"
)

const (
	helpHeaderUsage    = "Usage:"
	helpHeaderFlags    = "Flags:"
	helpHeaderExamples = "Examples:"
)

func printHelp() {
	fmt.Printf("vectos %s\n\n", buildinfo.Version)
	fmt.Println("Local-first code context engine for AI agents.")
	fmt.Println()
	fmt.Println(helpHeaderUsage)
	fmt.Println("  vectos <command> [arguments]")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  index   <path>   Index a file or directory with semantic embeddings")
	fmt.Println("  search  <query>  Search the index using semantic or keyword search")
	fmt.Println("  benchmark <file> Run retrieval benchmarks against an indexed project")
	fmt.Println("  status           Show index status for the current project")
	fmt.Println("  mcp              Start the MCP server for agent clients")
	fmt.Println("  doctor           Run installation and runtime diagnostics")
	fmt.Println("  serve            Start the HTTP server for programmatic reindex triggers")
	fmt.Println("  setup   <agent>  Configure Vectos for a supported agent client")
	fmt.Println("  version          Show version, commit, and build date")
	fmt.Println("  help             Show this help message")
	fmt.Println()
	fmt.Println("Use 'vectos help <command>' or 'vectos <command> --help' for command details.")
	fmt.Println()
	fmt.Println("Documentation index:")
	fmt.Println("  Use --docs with index, search, or status to operate on a separate")
	fmt.Println("  documentation index instead of the source code index.")
}

func printSubcommandHelp(cmd string) {
	switch cmd {
	case "index":
		fmt.Println(helpHeaderUsage)
		fmt.Println("  vectos index <path> [flags]")
		fmt.Println()
		fmt.Println("Index a file or directory. Generates semantic embeddings for all supported")
		fmt.Println("files and stores them in a project-scoped SQLite database.")
		fmt.Println()
		fmt.Println("Use --docs to index documentation files (.md, .rst, .adoc, .txt, etc.)")
		fmt.Println("into a separate docs database instead of the source code index.")
		fmt.Println()
		fmt.Println(helpHeaderFlags)
		fmt.Println("  --project <name>       Nx project name to scope the index and internal dependencies (optional)")
		fmt.Println("  --changed <paths>      Comma-separated changed file paths to refresh incrementally")
		fmt.Println("  --docs                 Index only documentation files into a separate docs database")
		fmt.Println("  --dimensions <num>     Embedding vector dimensions (default: 512)")
		fmt.Println()
		fmt.Println("Dimensions (Matryoshka Representation Learning):")
		fmt.Println("  jina-embeddings-v3 supports Matryoshka truncation, allowing you to trade")
		fmt.Println("  search quality for speed and storage. Valid values: 32, 64, 128, 256, 512, 768, 1024.")
		fmt.Println()
		fmt.Println("  Dimension  Quality (nDCG@10)  vs 1024d   Storage/vector")
		fmt.Println("  ─────────  ─────────────────  ─────────  ──────────────")
		fmt.Println("  1024       63.35%             baseline   4096 bytes")
		fmt.Println("   768       63.30%             −0.05      3072 bytes")
		fmt.Println("   512       63.16%             −0.19      2048 bytes  ← default")
		fmt.Println("   256       62.72%             −0.63      1024 bytes")
		fmt.Println("   128       61.64%             −1.71       512 bytes")
		fmt.Println("    64       58.54%             −4.81       256 bytes")
		fmt.Println("    32       52.54%            −10.81       128 bytes")
		fmt.Println()
		fmt.Println("  Recommended: 512 (default) for most projects. Use 256 for large monorepos")
		fmt.Println("  where speed matters. Use 1024 only if maximum retrieval precision is critical.")
		fmt.Println("  Changing dimensions triggers a full re-embedding of all files.")
		fmt.Println()
		fmt.Println("  Can also be set in ~/.vectos/config.json:")
		fmt.Println("    { \"embeddings\": { \"embedded\": { \"dimensions\": 256 } } }")
		fmt.Println()
		fmt.Println(helpHeaderExamples)
		fmt.Println("  vectos index .")
		fmt.Println("  vectos index ./src --project frontend")
		fmt.Println("  vectos index . --changed src/App.tsx,src/hooks/useAuth.ts")
		fmt.Println("  vectos index . --docs")
		fmt.Println("  vectos index . --dimensions 256")
		fmt.Println("  vectos index . --dimensions 1024")
	case "search":
		fmt.Println(helpHeaderUsage)
		fmt.Println("  vectos search <query> [flags]")
		fmt.Println()
		fmt.Println("Search the index using semantic similarity. Falls back to keyword search")
		fmt.Println("when semantic search is unavailable or returns no results.")
		fmt.Println()
		fmt.Println("Use --docs to search the documentation index instead of source code.")
		fmt.Println()
		fmt.Println(helpHeaderFlags)
		fmt.Println("  --project <name>   Nx project name to scope the search and internal dependencies (optional)")
		fmt.Println("  --full             Show full chunk content instead of compact snippets")
		fmt.Println("  --docs             Search documentation index instead of source code")
		fmt.Println()
		fmt.Println(helpHeaderExamples)
		fmt.Println("  vectos search \"checkout payment flow\"")
		fmt.Println("  vectos search \"auth middleware\" --project api")
		fmt.Println("  vectos search --docs \"getting started\"")
	case "status":
		fmt.Println(helpHeaderUsage)
		fmt.Println("  vectos status [flags]")
		fmt.Println()
		fmt.Println("Show index stats, embedding provider health, and reindex status for")
		fmt.Println("the current project.")
		fmt.Println()
		fmt.Println("Use --docs to inspect the documentation index instead of the source index.")
		fmt.Println()
		fmt.Println(helpHeaderFlags)
		fmt.Println("  --project <name>   Nx project name to inspect with internal dependency roots (optional)")
		fmt.Println("  --docs             Show documentation index status instead of source index")
		fmt.Println()
		fmt.Println(helpHeaderExamples)
		fmt.Println("  vectos status")
		fmt.Println("  vectos status --project frontend")
		fmt.Println("  vectos status --docs")
	case "benchmark":
		fmt.Println(helpHeaderUsage)
		fmt.Println("  vectos benchmark <file> [flags]")
		fmt.Println()
		fmt.Println("Run a repeatable retrieval benchmark against the current project's index.")
		fmt.Println("The benchmark file defines representative queries and expected useful")
		fmt.Println("files or chunks. Results report top-ranked hit rates for normal")
		fmt.Println("development iteration.")
		fmt.Println()
		fmt.Println(helpHeaderFlags)
		fmt.Println("  --project <name>   Nx project name to benchmark with internal dependency roots")
		fmt.Println()
		fmt.Println(helpHeaderExamples)
		fmt.Println("  vectos benchmark ./benchmarks/retrieval/vectos-core.json")
		fmt.Println("  vectos benchmark ./benchmarks/retrieval/app.json --project web")
	case "mcp":
		fmt.Println(helpHeaderUsage)
		fmt.Println("  vectos mcp")
		fmt.Println()
		fmt.Println("Start the MCP server over stdio. Exposes the following tools to")
		fmt.Println("compatible agent clients (e.g. OpenCode, Claude, Codex):")
		fmt.Println()
		fmt.Println("  search_code    Search the codebase using semantic search with keyword fallback")
		fmt.Println("  search_docs    Search project documentation using semantic search")
		fmt.Println("  index_project  Index a directory to make it searchable via semantic embeddings")
		fmt.Println("  list_projects  List available Nx project names in the workspace")
		fmt.Println()
		fmt.Println("Logs are written to ~/.vectos/vectos-mcp.log to avoid polluting stdio.")
	case "doctor":
		fmt.Println(helpHeaderUsage)
		fmt.Println("  vectos doctor")
		fmt.Println()
		fmt.Println("Run installation, provider, and index diagnostics for the current")
		fmt.Println("project. Checks configuration, embedding model availability, provider")
		fmt.Println("health, and index consistency. Exits with code 0 when all critical")
		fmt.Println("checks pass, non-zero otherwise.")
		fmt.Println()
		fmt.Println("This command is read-only and safe to run at any time.")
	case "serve":
		fmt.Println(helpHeaderUsage)
		fmt.Println("  vectos serve [flags]")
		fmt.Println()
		fmt.Println("Start an HTTP server that keeps the embedding model and SQLite connections")
		fmt.Println("in memory across requests. Exposes the following endpoints:")
		fmt.Println()
		fmt.Println("  GET  /health    Liveness check, returns {\"status\": \"ok\"} (200) or {\"status\": \"starting\"} (503)")
		fmt.Println("  POST /reindex   Trigger incremental or full reindex via JSON body")
		fmt.Println()
		fmt.Println("The /reindex endpoint accepts:")
		fmt.Println("  {\"path\": \"/project/dir\", \"changed\": \"file1.go,file2.md\", \"project\": \"my-app\", \"docs\": true}")
		fmt.Println()
		fmt.Println("Logs are written to ~/.vectos/vectos-serve.log.")
		fmt.Println("\nWatch Mode:")
		fmt.Println("  vectos serve automatically watches the project directory for file changes")
		fmt.Println("  and triggers incremental reindexing to keep the index in sync.")
		fmt.Println("  Enabled by default; use --watch=false to disable.")
		fmt.Println("  Multiple rapid changes are batched with --watch-debounce (default 500ms).")
		fmt.Println("  Use --watch-ignore for comma-separated glob patterns such as .git,node_modules,*.lock.")
		fmt.Println()
		fmt.Println(helpHeaderFlags)
		fmt.Println("  --port <num>              Port to listen on (default 7438, overridable via VECTOS_PORT env var)")
		fmt.Println("  --project-base-dir <dir>  Directory for project index databases (default ~/.vectos/projects)")
		fmt.Println("  --watch              enable automatic reindex on file changes (default: true)")
		fmt.Println("  --watch-debounce     debounce delay for file change events (default: 500ms)")
		fmt.Println("  --watch-ignore       comma-separated glob patterns to ignore (default: .git,node_modules,*.lock)")
		fmt.Println()
		fmt.Println(helpHeaderExamples)
		fmt.Println("  vectos serve")
		fmt.Println("  vectos serve --port 8080")
		fmt.Println("  vectos serve --project-base-dir /tmp/vectos-projects")
		fmt.Println("  VECTOS_PORT=8080 vectos serve")
	case "setup":
		fmt.Println(helpHeaderUsage)
		fmt.Println("  vectos setup <agent> [--uninstall] [--yes] [--no-guidance]")
		fmt.Println()
		fmt.Println("Configure or remove Vectos MCP integration for a supported agent client.")
		fmt.Println("Installs global guidance so the agent prefers Vectos")
		fmt.Println("search tools before falling back to generic file-search tools.")
		fmt.Println()
		fmt.Println("Supported agents:")
		fmt.Println("  opencode")
		fmt.Println("  claude")
		fmt.Println("  codex")
		fmt.Println()
		fmt.Println(helpHeaderFlags)
		fmt.Println("  --uninstall      Remove the Vectos MCP entry and managed guidance for the selected agent")
		fmt.Println("  --yes, -y        Answer yes to all prompts (non-interactive mode)")
		fmt.Println("  --no-guidance    Skip global guidance updates")
		fmt.Println()
		fmt.Println(helpHeaderExamples)
		fmt.Println("  vectos setup opencode")
		fmt.Println("  vectos setup claude")
		fmt.Println("  vectos setup codex")
		fmt.Println("  vectos setup opencode --uninstall")
		fmt.Println("  vectos setup opencode --no-guidance")
	case "version":
		fmt.Println(helpHeaderUsage)
		fmt.Println("  vectos version")
		fmt.Println()
		fmt.Println("Print the release version, git commit, and build date.")
	default:
		fmt.Printf("unknown command: %s\n", cmd)
		fmt.Println("Run 'vectos help' for a list of available commands.")
		os.Exit(1)
	}
}
