package main

import (
	"fmt"
	"os"

	"vectos/internal/buildinfo"
)

func printHelp() {
	fmt.Printf("vectos %s\n\n", buildinfo.Version)
	fmt.Println("Local-first code context engine for AI agents.")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  vectos <command> [arguments]")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  index   <path>   Index a file or directory with semantic embeddings")
	fmt.Println("  search  <query>  Search the index using semantic or keyword search")
	fmt.Println("  benchmark <file> Run retrieval benchmarks against an indexed project")
	fmt.Println("  status           Show index status for the current project")
	fmt.Println("  mcp              Start the MCP server for agent clients")
	fmt.Println("  setup   <agent>  Configure Vectos for a supported agent client")
	fmt.Println("  version          Show version, commit, and build date")
	fmt.Println("  help             Show this help message")
	fmt.Println()
	fmt.Println("Use 'vectos help <command>' or 'vectos <command> --help' for command details.")
}

func printSubcommandHelp(cmd string) {
	switch cmd {
	case "index":
		fmt.Println("Usage:")
		fmt.Println("  vectos index <path> [flags]")
		fmt.Println()
		fmt.Println("Index a file or directory. Generates semantic embeddings for all supported")
		fmt.Println("files and stores them in a project-scoped SQLite database.")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --project <name>   Nx project name to scope the index (optional)")
		fmt.Println("  --changed <paths>  Comma-separated changed file paths to refresh incrementally")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos index .")
		fmt.Println("  vectos index ./src --project my-app")
		fmt.Println("  vectos index . --changed src/App.tsx,src/hooks/useAuth.ts")
	case "search":
		fmt.Println("Usage:")
		fmt.Println("  vectos search <query> [flags]")
		fmt.Println()
		fmt.Println("Search the index using semantic similarity. Falls back to keyword search")
		fmt.Println("when semantic search is unavailable or returns no results.")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --project <name>   Nx project name to scope the search (optional)")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos search \"checkout payment flow\"")
		fmt.Println("  vectos search \"auth middleware\" --project api")
	case "status":
		fmt.Println("Usage:")
		fmt.Println("  vectos status [flags]")
		fmt.Println()
		fmt.Println("Show index stats, embedding provider health, and reindex status for")
		fmt.Println("the current project.")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --project <name>   Nx project name to inspect (optional)")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos status")
		fmt.Println("  vectos status --project my-app")
	case "benchmark":
		fmt.Println("Usage:")
		fmt.Println("  vectos benchmark <file> [flags]")
		fmt.Println()
		fmt.Println("Run a repeatable retrieval benchmark against the current project's index.")
		fmt.Println("The benchmark file defines representative queries and expected useful")
		fmt.Println("files or chunks. Results report top-ranked hit rates for normal")
		fmt.Println("development iteration.")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --project <name>   Nx project name to benchmark when inside an Nx workspace")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos benchmark ./benchmarks/retrieval/vectos-core.json")
		fmt.Println("  vectos benchmark ./benchmarks/retrieval/app.json --project web")
	case "mcp":
		fmt.Println("Usage:")
		fmt.Println("  vectos mcp")
		fmt.Println()
		fmt.Println("Start the MCP server over stdio. Exposes vectos_index_project and")
		fmt.Println("vectos_search_code tools to compatible agent clients (e.g. OpenCode).")
		fmt.Println()
		fmt.Println("Logs are written to ~/.vectos/vectos-mcp.log to avoid polluting stdio.")
	case "setup":
		fmt.Println("Usage:")
		fmt.Println("  vectos setup <agent> [--uninstall]")
		fmt.Println()
		fmt.Println("Configure or remove Vectos MCP integration for a supported agent client.")
		fmt.Println("Optionally installs global guidance so the agent prefers Vectos")
		fmt.Println("search tools before falling back to generic file-search tools.")
		fmt.Println()
		fmt.Println("Supported agents:")
		fmt.Println("  opencode")
		fmt.Println("  claude")
		fmt.Println("  codex")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --uninstall   Remove the Vectos MCP entry and managed guidance for the selected agent")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos setup opencode")
		fmt.Println("  vectos setup claude")
		fmt.Println("  vectos setup codex")
		fmt.Println("  vectos setup opencode --uninstall")
	case "version":
		fmt.Println("Usage:")
		fmt.Println("  vectos version")
		fmt.Println()
		fmt.Println("Print the release version, git commit, and build date.")
	default:
		fmt.Printf("unknown command: %s\n", cmd)
		fmt.Println("Run 'vectos help' for a list of available commands.")
		os.Exit(1)
	}
}
