package main

import (
	"fmt"
	"os"

	"vectos/internal/buildinfo"
)

func printHelp() {
	fmt.Printf("vectos %s\n\n", buildinfo.Version)
	fmt.Println("Local-first code context engine for AI agents.")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  vectos <command> [arguments]")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  index   <path>   Index a file or directory with semantic embeddings")
	fmt.Println("  search  <query>  Search the index using semantic or keyword search")
	fmt.Println("  benchmark <file> Run retrieval benchmarks against an indexed project")
	fmt.Println("  status           Show index status for the current project")
	fmt.Println("  mcp              Start the MCP server for agent clients")
	fmt.Println("  setup   <agent>  Configure Vectos for a supported agent client")
	fmt.Println("  version          Show version, commit, and build date")
	fmt.Println("  help             Show this help message")
	fmt.Println()
	fmt.Println("Use 'vectos help <command>' or 'vectos <command> --help' for command details.")
	fmt.Println()
	fmt.Println("Documentation index:")
	fmt.Println("  Use --docs with index, search, or status to operate on a separate")
	fmt.Println("  documentation index instead of the source code index.")
}

func printSubcommandHelp(cmd string) {
	switch cmd {
	case "index":
		fmt.Println("Usage:")
		fmt.Println("  vectos index <path> [flags]")
		fmt.Println()
		fmt.Println("Index a file or directory. Generates semantic embeddings for all supported")
		fmt.Println("files and stores them in a project-scoped SQLite database.")
		fmt.Println()
		fmt.Println("Use --docs to index documentation files (.md, .rst, .adoc, .txt, etc.)")
		fmt.Println("into a separate docs database instead of the source code index.")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --project <name>   Nx project name to scope the index and internal dependencies (optional)")
		fmt.Println("  --changed <paths>  Comma-separated changed file paths to refresh incrementally")
		fmt.Println("  --docs             Index only documentation files into a separate docs database")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos index .")
		fmt.Println("  vectos index ./src --project frontend")
		fmt.Println("  vectos index . --changed src/App.tsx,src/hooks/useAuth.ts")
		fmt.Println("  vectos index . --docs")
	case "search":
		fmt.Println("Usage:")
		fmt.Println("  vectos search <query> [flags]")
		fmt.Println()
		fmt.Println("Search the index using semantic similarity. Falls back to keyword search")
		fmt.Println("when semantic search is unavailable or returns no results.")
		fmt.Println()
		fmt.Println("Use --docs to search the documentation index instead of source code.")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --project <name>   Nx project name to scope the search and internal dependencies (optional)")
		fmt.Println("  --full             Show full chunk content instead of compact snippets")
		fmt.Println("  --docs             Search documentation index instead of source code")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos search \"checkout payment flow\"")
		fmt.Println("  vectos search \"auth middleware\" --project api")
		fmt.Println("  vectos search --docs \"getting started\"")
	case "status":
		fmt.Println("Usage:")
		fmt.Println("  vectos status [flags]")
		fmt.Println()
		fmt.Println("Show index stats, embedding provider health, and reindex status for")
		fmt.Println("the current project.")
		fmt.Println()
		fmt.Println("Use --docs to inspect the documentation index instead of the source index.")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --project <name>   Nx project name to inspect with internal dependency roots (optional)")
		fmt.Println("  --docs             Show documentation index status instead of source index")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos status")
		fmt.Println("  vectos status --project frontend")
		fmt.Println("  vectos status --docs")
	case "benchmark":
		fmt.Println("Usage:")
		fmt.Println("  vectos benchmark <file> [flags]")
		fmt.Println()
		fmt.Println("Run a repeatable retrieval benchmark against the current project's index.")
		fmt.Println("The benchmark file defines representative queries and expected useful")
		fmt.Println("files or chunks. Results report top-ranked hit rates for normal")
		fmt.Println("development iteration.")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --project <name>   Nx project name to benchmark with internal dependency roots")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos benchmark ./benchmarks/retrieval/vectos-core.json")
		fmt.Println("  vectos benchmark ./benchmarks/retrieval/app.json --project web")
	case "mcp":
		fmt.Println("Usage:")
		fmt.Println("  vectos mcp")
		fmt.Println()
		fmt.Println("Start the MCP server over stdio. Exposes the following tools to")
		fmt.Println("compatible agent clients (e.g. OpenCode, Claude, Codex):")
		fmt.Println()
		fmt.Println("  search_code    Search the codebase using semantic search with keyword fallback")
		fmt.Println("  search_docs    Search project documentation using semantic search")
		fmt.Println("  index_project  Index a directory to make it searchable via semantic embeddings")
		fmt.Println("  list_projects  List available Nx project names in the workspace")
		fmt.Println()
		fmt.Println("Logs are written to ~/.vectos/vectos-mcp.log to avoid polluting stdio.")
	case "setup":
		fmt.Println("Usage:")
		fmt.Println("  vectos setup <agent> [--uninstall]")
		fmt.Println()
		fmt.Println("Configure or remove Vectos MCP integration for a supported agent client.")
		fmt.Println("Optionally installs global guidance so the agent prefers Vectos")
		fmt.Println("search tools before falling back to generic file-search tools.")
		fmt.Println()
		fmt.Println("Supported agents:")
		fmt.Println("  opencode")
		fmt.Println("  claude")
		fmt.Println("  codex")
		fmt.Println()
		fmt.Println("Flags:")
		fmt.Println("  --uninstall   Remove the Vectos MCP entry and managed guidance for the selected agent")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  vectos setup opencode")
		fmt.Println("  vectos setup claude")
		fmt.Println("  vectos setup codex")
		fmt.Println("  vectos setup opencode --uninstall")
	case "version":
		fmt.Println("Usage:")
		fmt.Println("  vectos version")
		fmt.Println()
		fmt.Println("Print the release version, git commit, and build date.")
	default:
		fmt.Printf("unknown command: %s\n", cmd)
		fmt.Println("Run 'vectos help' for a list of available commands.")
		os.Exit(1)
	}
}
